[tool.poetry]
name = "tap-contentquo"
version = "0.0.1"
description = "`tap-contentquo` is a Singer tap for HubSpot, built with the Meltano Singer SDK"
authors = ["Derek Visch <dvisch@autoidm.com>"]
license = "Apache v2"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
requests = "^2.32.4"
# Update Singer SDK to the latest version with the [jwt] extra
singer-sdk = { version = "^0.53.5", extras = ["jwt"] }
# Add the latest PyJWT
pyjwt = "^2.11.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.4"
flake8 = "^3.9.2"
black = "^21.9b0"
pydocstyle = "^6.1.1"
mypy = "^0.910"
types-requests = "^2.26.1"
isort = "^5.10.1"

[tool.poetry.group.dev.dependencies]
viztracer = "^0.15.4"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_contentquo"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-contentquo = 'tap_contentquo.tap:cli'
